#!/bin/bash

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo ""
echo "Running migrations"
${OPENSHIFT_REPO_DIR}manage.py syncdb --noinput
${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

echo ""
echo "Collecting static files"
if [ ! -d ${OPENSHIFT_REPO_DIR}wsgi/static ]
then
    mkdir -p ${OPENSHIFT_REPO_DIR}wsgi/static
fi

${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput -v0 -l
