[pytest]
DJANGO_SETTINGS_MODULE = homeapps.settings.pytest
addopts = --headed
markers =
    unit: Unit tests that don't need a browser
    behavior: Browser-based behavior tests
    wip: mark test as work in progress
