# Generated by Django 5.2.14 on 2026-06-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricGasStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electric_used', models.PositiveIntegerField(help_text='(in kWh)')),
                ('gas_used', models.PositiveIntegerField(help_text='(in ccf)')),
                ('statement_date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'electric & gas',
                'verbose_name_plural': 'Electric/Gas',
                'ordering': ['statement_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('water_used', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Water',
                'ordering': ['from_date'],
                'unique_together': {('from_date', 'to_date')},
            },
        ),
    ]
