# Generated by Django 5.2.14 on 2026-06-07 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waterstatement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electricgasstatement',
            name='user',
            field=models.ForeignKey(default=None, help_text='To which user this item belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterstatement',
            name='user',
            field=models.ForeignKey(default=None, help_text='To which user this item belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricgasstatement',
            name='statement_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='electricgasstatement',
            unique_together={('user', 'statement_date')},
        ),
        migrations.AlterUniqueTogether(
            name='waterstatement',
            unique_together={('user', 'from_date', 'to_date')},
        ),
    ]
