# Generated by Django 5.2.14 on 2026-06-02 12:29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_account_amount_alter_account_amount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Amount the bill is for.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='Income amount.', max_digits=10),
        ),
    ]
