# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20220914_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Account Transfer'), (5, 'ACH - Direct Debit'), (6, 'ATM'), (7, 'Cash'), (0, 'Check'), (1, 'Credit Card: Discover'), (2, 'Credit Card: Mastercard'), (3, 'Credit Card: VISA')], help_text='How bill was paid', null=True),
        ),
    ]
